[grid]
n = 128
L = 256.0

[time]
dt = 0.001
steps = 1000

[output]
append_output   = false        # optional, this is the default
output_filename = "energy.dat" # optional, this is the default
output_every    = 100
conf_every      = 1000

[integrator]
name       = "euler"

[[fields]]
name = "phi"
initialisation = "random"
average = 0.0
random_stddev = 0.05

[[fields]]
name = "c"
initialisation = "constant"
average = 1e-3

# ===== Terms =====
[[terms]]
id      = "ch_phi"
kind    = "CH"                # term type (registered key)
target  = "phi"               # which field it updates
enabled = true
kappa = 1.0

  [terms.ops]                 # which discretization backend this term uses
  type = "fd"                 # "fd" | "spectral" (not implemented yet)

  [terms.free_energy]
  type = "landau"             # registered FE key
  eps = 0.8

  [terms.mobility]
  type = "const"              # "const" | "exp_of_field"
  M0 = 1.0

[[terms]]
id      = "ac_c"
kind    = "AC"
target  = "c"
enabled = false

  [terms.ops]
  type = "fd"

  [terms.free_energy]
  type  = "gel"            # registered FE key for AC
  Mc    = 0.1
  gcoef = 1.0

  [terms.coupling]
  driver = "phi"              # AC uses g(phi) in dF/dc
